### ISSUE TITLE
Two scheduled pinning script tasks?

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge-maintenance#10]
Appears there are two pinning jobs (last two) that run ~1.5hrs apart. Not sure why we need 2 of them. Maybe one of them can be converted to a linter job. Thoughts @pelson ?

<img width="1554" alt="screen shot 2016-10-06 at 2 41 54" src="https://cloud.githubusercontent.com/assets/3019665/19142869/86286bc2-8b6e-11e6-93ce-512b274d9d5f.png">

**Comment by pelson** [comment]
Thanks @jakirkham. I have removed the one that wasn't coming directly from the github repo. Easy enough to add another job if we want. Are you suggesting the "raise an issue if a feedstock has lint" script?

**Comment by jakirkham** [comment]
Yeah, that was my thinking, but it's not a big deal either way.

Should add that re-rendering seems to still be set to 5 there. Though I'm not sure if that is where the setting is coming from or not.

**Comment by jakirkham** [comment]
Closing as this has been resolved.
