### ISSUE TITLE
Add cron job for conda-forge.github.io runs

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge-maintenance#2]
This basically replaces this issue ( https://github.com/conda-forge/conda-forge.github.io/issues/48 ) for creating cron jobs. The purpose would be to trigger CI builds of the conda-forge.github.io feedstocks script periodically. Perhaps every 24 hours to begin with.

**Comment by pelson** [comment]
@jakirkham - happy with nightlies, or do you want to pull https://github.com/conda-forge/conda-forge.github.io/issues/48#issuecomment-226571553 into here?

**Comment by jakirkham** [comment]
Nope. I think I wasn't convinced it was working at the time. Clearly convinced now and am more than happy with nightlies. Thanks for the reminder. Closing...

**Comment by jakirkham** [comment]
Travis CI has added their own functionality for this. I enabled it a while back and it has worked fine. Today have disabled nightli.es. Let's see how it goes from here.
