### ISSUE TITLE
Pinning PRs should be opened in non-random order

### ISSUE THREAD

**Issue by rgommers** [conda-forge/conda-forge-maintenance#20]
Currently PRs are opened 5 at a time, in a random order. This gives issues, recent example was when OpenBLAS was updated from 0.2.18 to 0.2.19, a PR to ``scipy-feedstock`` was opened before a PR to ``numpy-feedstock``. This caused the ``scipy`` build to pick up ``numpy`` from ``defaults``, which led to segfaults in the CircleCI build.

@jakirkham suggested a topological sort before opening pinning PRs: https://github.com/conda-forge/scipy-feedstock/pull/38#issuecomment-260975428

**Comment by jakirkham** [comment]
This is handled now by [making a migrator]( https://conda-forge.org/docs/maintainer/pinning_deps.html#propagate-pin-changes-with-a-migrator ), the migration bot uses to add dependencies in topological order. Any issues with the bot can be [filed on this issue tracker]( https://github.com/regro/cf-scripts/issues ).
