### ISSUE TITLE
Conda-forge organization permissions

### ISSUE THREAD

**Issue by amueller** [conda-forge/conda-forge-maintenance#26]
Hi y'all. Not sure where to post a conda-forge issue.
The organization currently has a setting that means any member of the organization will automatically give access to this organization to every github application they authorize.
That's bad because:
* security - if any of the members authorizes a bad apple, we might be screwed.
* every application that I'm using with github will show me *all conda-forge repositories* as my repositories. That's pretty annoying on readthedocs, for example.

You can change that here:
https://github.com/organizations/conda-forge/settings/oauth_application_policy

**Comment by jakirkham** [comment]
> Not sure where to post a conda-forge issue.

Probably not, but let's leave it here for now.

> ...give access to this permission...

Sorry this is kind of vague. What permission?

**Comment by amueller** [comment]
sorry, *give access to this organization*

**Comment by amueller** [comment]
Like if any of the 348 members has authorized an application, like travis ci or one of the 100 code checkers or review tools, on any of their repositories, it will automatically also be authorized for conda-forge. Given the current setting, it's not possible for a user to not give authorization for this organization.

**Comment by amueller** [comment]
You will need to explicitly enable the CI that's actually used, though.

**Comment by jakirkham** [comment]
So right now it requires admin approval to add any new application to conda-forge. A user can't just add a new application to conda-forge that we haven't approved. Just checked the settings and verified this is true.

**Comment by jakirkham** [comment]
That said, we do have ReadTheDocs enabled for the org as we were using it to build docs. One can import a repo manually as a near term workaround.

As far as the future of RTD at conda-forge, I think @scopatz has changed things so we are building a copy of the docs with Travis CI and pushing it to our webpage repo. So, I don't think we need RTD any more. We should be able to disable it unless anyone has strong opposition. Thoughts @conda-forge/core?

**Comment by amueller** [comment]
hm ok I might have been mislead wrt your security settings by you having rtd enabled, sorry about that.

**Comment by jakirkham** [comment]
Not a problem. Though I definitely hear you that having gobs of repos like we do makes it a pain to navigate through enabling new repos for a service. I think the RTD situation might improve for others (though myself and others will still run into this issue bc forks 😄) if they add a filter for user repos along with the org filters. That said, RTD has gotten a lot better with loading a list with gobs of repos. It use to freeze my browser.

**Comment by jakirkham** [comment]
I've opened an issue on the webpage repo about closing down RTD for the org. Will close this issue as it seems that change will solve the problems experienced here. Please let me know if there is any other concern(s) that I may have missed.

xref: https://github.com/conda-forge/conda-forge.github.io/issues/323
