### ISSUE TITLE
number of package updates is incorrect

### ISSUE THREAD

**Issue by kain88-de** [conda-forge/conda-forge-maintenance#27]
The readme states that only 5 packages are updated at once. According to @jakirkham the current limit is 20. It would also be interesting to know how often this script is run on heroku.

**Comment by jakirkham** [comment]
...by which you are referring to re-renderings correct?

**Comment by kain88-de** [comment]
Yes. The script only does rerenderings as I understand it.

**Comment by jakirkham** [comment]
Yeah, there is one to do pinnings too. We need to update that in the Readme as well.

**Comment by jakirkham** [comment]
This is no longer used for re-renderings. Instead we use a bot to handle re-renderings and other feedstock updates based on user request. Please see [these docs]( https://conda-forge.org/docs/maintainer/infrastructure.html#admin-web-services ) for more details.
