### ISSUE TITLE
[Feature]: Auto-assign MNT PR's to maintainers.

### ISSUE THREAD

**Issue by sodre** [conda-forge/conda-forge-maintenance#44]
I would like for the conda-forge-maintenance' PRs to be  auto-assigned to the feedstock maintainers.  

As the number of feedstocks grow for a given maintainer it is hard to find all the PRs that are pending. This change would allow maintainers to simply click at Pull Requests in the GitHub toolbar and find everything that is pending.

I could see this feature being expanded to include auto-assigning any issue opened within a feedstock as well as outside PRs.

**Comment by jakirkham** [comment]
It's an interesting idea. That could be pretty useful.

Also you might want to checkout [All my pulls]( https://github.com/minrk/all-my-pulls ), which @minrk wrote. This allows one to see all pull requests open on their repos.

**Comment by jakirkham** [comment]
This was done by adding codeowners ( https://github.com/conda-forge/conda-smithy/pull/1086 )
