### ISSUE TITLE
The batch file cannot be found.

### ISSUE THREAD

**Issue by horta** [conda-forge/conda-forge-maintenance#46]
Windows builds are erroring:

- https://github.com/conda-forge/zstd-feedstock/pull/6
- https://ci.appveyor.com/project/conda-forge/openturns-feedstock
- https://ci.appveyor.com/project/conda-forge/rsgislib-feedstock/build/job/7casgops4ocdnsmx

**Comment by isuruf** [comment]
A rerendering should fix it. Btw, you should open such issues in the future in the webpage repo.

**Comment by arsenovic** [comment]
i get this error too. what is re-rendering and how do i do it?

**Comment by ocefpaf** [comment]
> i get this error too. what is re-rendering 

https://conda-forge.org/docs/conda_smithy.html

> and how do i do it?

https://conda-forge.org/docs/webservice.html#conda-forge-admin-please-rerender
