### ISSUE TITLE
conda failed to solve environment after using wildcard in package name

### ISSUE THREAD

**Issue by xujiboy** [conda-forge/conda-forge-maintenance#48]
Hi Conda/Conda-Forge community,

First let me apologize if this is not the right place to report this issue, and if it is not please let me know where I should. 

I recently experienced a conda fail of solving environment after using a wildcard in a package name. 

**What I did:**
`conda install dash-*-components` 
I was hoping that conda can find both `dash-core-components` and `dash-html-components` but it only installed one and I was able to install the other one by specifying the whole name of the package. 

**What problem I am facing now:**
After that I haven't been able to `conda install `anything and always get `CondaError`.  An example error message is pasted below:
```
Jis-MacBook-Pro-Work:app_layout_tester ji$ conda install ipython
Solving environment: failed

CondaError: Conda encountered an error with your environment.  Please report an issue
at https://github.com/conda/conda/issues/new.  In your report, please include
the output of 'conda info' and 'conda list' for the active environment, along
with the command you invoked that resulted in this error.
  pkg_name: *
  spec: dash-*-components
  matches_for_spec: 
    - conda-forge::dash-html-components-0.11.0-py_0
    - conda-forge::dash-core-components-0.28.0-py_0
```
So what should I do now, instead of delete my current env and re-create one?

Best,
Ji

**Comment by msarahan** [comment]
This issue belongs on the conda issue tracker:  https://github.com/conda/conda

**Comment by xujiboy** [comment]
Thanks @msarahan
