### ISSUE TITLE
Pin script opened a build number bump...

### ISSUE THREAD

**Issue by pelson** [conda-forge/conda-forge-maintenance#6]
https://github.com/conda-forge/blas-feedstock/pull/2

**Comment by jakirkham** [comment]
Also these PRs.

* https://github.com/conda-forge/mpfr-feedstock/pull/12
* https://github.com/conda-forge/qt-feedstock/pull/31
* https://github.com/conda-forge/r-base-feedstock/pull/13
* https://github.com/conda-forge/qt-feedstock/pull/32
* https://github.com/conda-forge/glpk-feedstock/pull/20
* https://github.com/conda-forge/ffmpeg-feedstock/pull/24
* https://github.com/conda-forge/ffmpeg-feedstock/pull/29
* https://github.com/conda-forge/swig-feedstock/pull/16
* https://github.com/conda-forge/swig-feedstock/pull/15
* https://github.com/conda-forge/graphviz-feedstock/pull/10
* https://github.com/conda-forge/symengine-feedstock/pull/8
* https://github.com/conda-forge/pandoc-feedstock/pull/16
* https://github.com/conda-forge/fmipp-feedstock/pull/8
* https://github.com/conda-forge/gmpy2-feedstock/pull/7
* https://github.com/conda-forge/opencv-feedstock/pull/67

**Comment by jakirkham** [comment]
...and https://github.com/conda-forge/qt-feedstock/pull/31

**Comment by isuruf** [comment]
`gmpy2`, `symengine` and `mpfr` all had a package `- gmp   # [unix]` requirement and the update pinning script had `gmp >=5.0.1,<7`
Packages with just `- gmp` were updated correctly

**Comment by jakirkham** [comment]
So you are thinking the selector somehow messes this up? It's an interesting theory. Will try to follow up on when I have more time.

**Comment by isuruf** [comment]
See my comment here, https://github.com/conda-forge/conda-forge.github.io/commit/483127828ea72dd4e7ed4def7a3c13211762171b#commitcomment-21422081

**Comment by jakirkham** [comment]
We migrated from the pinning script to [conda-forge-pinning]( https://github.com/conda-forge/conda-forge-pinning-feedstock ) as part of migrating to conda-build 3. Also we including pinnings as part of re-rendering. So this shouldn't be relevant any more.
