### ISSUE TITLE
Pin script overwrote whole recipe

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge-maintenance#8]
In PR ( https://github.com/conda-forge/backports.functools_lru_cache-feedstock/pull/1 ), it appears the pinning script ran against a recipe with no pinnings and changed the entire thing in a nearly imperceptible way.

**Comment by jakirkham** [comment]
I think your bad line feeds assumption is a good one, @pelson. Checked it out locally and looked at the diff for word changes and found none. This indicative of whitespace changes.

Edit: Also see below.

``` bash
$ file meta.yaml 
meta.yaml: ASCII text, with CRLF line terminators
```

**Comment by jakirkham** [comment]
Seem to have generated the same result by fixing the line feeds in PR ( https://github.com/conda-forge/backports.functools_lru_cache-feedstock/pull/3 ). Maybe this will lend some clues as to how to address this issue.

**Comment by pelson** [comment]
In many ways, I value that change - getting consistent line-endings is a worthy task (especially as we can't _see_ when it is a problem, and the majority of our recipes have LF, not CR). I'm not sure we _want_ to change anything here...

**Comment by jakirkham** [comment]
Windows users may disagree. 😀

In any event, I'm not worried about this any more as we know what is going on. Doing anything with this would be tedious, possibly create new problems, and detract from more important issues at conda-forge. This exists purely for documentation AFAIAC and would be just as happy to close it at this point.

**Comment by jakirkham** [comment]
So a good way to fix this as suggested by @goanpeca is to configuring the correct line endings with `.gitattributes`. Can do that with future feedstocks using the change presented in PR ( https://github.com/conda-forge/conda-smithy/pull/380 ). Also can make sure things enter `staged-recipes` with proper line endings with PR ( https://github.com/conda-forge/staged-recipes/pull/1920 ).

**Comment by jakirkham** [comment]
As of `conda-smithy` version `1.6.0`, we now include `.gitattributes` in feedstocks. Also, in `staged-recipes`, we include `.gitattributes` as well. These specify that LF be used for `meta.yaml` and `build.sh`; and these specify CRLF be used for `bld.bat`. Hopefully this should eliminate this sort of issue going forward regardless of OS used.
